// Generated by IcedCoffeeScript 1.6.2d
(function() {
  var app, fs, gate, gui, iced, nedb, __iced_k, __iced_k_noop;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  fs = require('fs-extra');

  gate = require('gate');

  nedb = require('nedb');

  gui = require('nw.gui');

  gui.Window.get().showDevTools();

  app = angular.module('editor', ['ui.bootstrap', 'ui.state']);

  app.config(function($stateProvider) {
    return $stateProvider.state('startup', {
      url: '',
      views: {
        root: {
          templateUrl: 'template/startup.html',
          controller: function($scope) {
            $scope.prevProjCtrl = function($scope) {
              return $scope.projects = [['The Life', 'D:/Encouragement_System']];
            };
            return $scope.newProjCtrl = function($scope) {
              return $scope.selectDir = function() {
                var elem;
                elem = $('#choose_dir');
                elem.change(function(e) {
                  var path, ___iced_passed_deferral, __iced_deferrals, __iced_k,
                    _this = this;
                  __iced_k = __iced_k_noop;
                  ___iced_passed_deferral = iced.findDeferral(arguments);
                  path = $(this).val();
                  (function(__iced_k) {
                    __iced_deferrals = new iced.Deferrals(__iced_k, {
                      parent: ___iced_passed_deferral,
                      filename: "app.coffee"
                    });
                    global.dbs.system.update({
                      type: 'proj_conf',
                      key: 'name'
                    }, {
                      value: $scope.proj_name
                    }, {
                      upsert: true
                    }, d.intercept(__iced_deferrals.defer({
                      lineno: 29
                    })));
                    __iced_deferrals._fulfill();
                  })(function() {
                    if (localStorage.last1 != null) {
                      localStorage.last2 = localStorage.last1;
                    }
                    return localStorage.last1 = JSON.stringify([path, $scope.proj_name]);
                  });
                });
                return elem.trigger('click');
              };
            };
          }
        }
      }
    });
  });

}).call(this);
